"""scenes_kit v3.0.0: eight animated hero scenes (inline SVG + CSS keyframes, no JS) with their
captions and speaker notes in three locales. Each scene is a recipe for a kind of motion:
1 sequence reveal on a timeline, 2 typing in / result out, 3 converge into one, 4 pass or bounce,
5 loop ring with a traveling dot, 6 packets traveling on lanes, 7 toggles and a lock, 8 rising steps."""
import re
from visual_layer import ico
LOCS = ['en', 'pt-BR', 'es']
RED, YEL, BLU, GRN = 'var(--ps-color-ms-red-500)', 'var(--ps-color-ms-yellow-500)', 'var(--ps-color-ms-blue-500)', 'var(--ps-color-ms-green-500)'
INK3 = 'var(--ps-color-ink-3)'

def T(x, y, s, cls='m', anchor='start', extra=''):
    return f'<text class="{cls}" x="{x}" y="{y}" text-anchor="{anchor}" {extra}>{s}</text>'
def R(x, y, w, hh, fill='var(--ps-color-paper)', stroke='var(--ps-color-rule-2)', rx=8, extra=''):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{hh}" rx="{rx}" fill="{fill}" stroke="{stroke}" stroke-width="1.2" {extra}/>'
def G(cls, d, inner, extra=''):
    return f'<g class="{cls}" style="--d:{d}" {extra}>{inner}</g>'
def ICON(name, x, y, size=24, color=INK3):
    return f'<svg x="{x}" y="{y}" width="{size}" height="{size}" viewBox="0 0 24 24" style="color:{color}"><use href="#i-{name}"/></svg>'
def PILL(x, y, w, txt, col, d, cls='a-pop'):
    """The pill grows to fit its label and stays centred on the same point: a caption never leaves its frame."""
    cx = x + w / 2
    w = max(w, round(len(txt) * 7.35) + 28)
    x = cx - w / 2
    return G(cls, d, R(x, y, w, 26, f'color-mix(in srgb, {col} 16%, transparent)', col, 13) + T(cx, y + 17, txt, 'm m--b', 'middle', f'style="fill:{col}"'))

EVENTS = ['sessionStart', 'userPromptSubmitted', 'userPromptTransformed', 'permissionRequest', 'preToolUse', 'postToolUse', 'postToolUseFailure', 'agentStop', 'subagentStart', 'subagentStop', 'preCompact', 'errorOccurred', 'notification', 'sessionEnd']
BLOCK = {'permissionRequest', 'preToolUse', 'agentStop'}

# ------------------------------------------------------------------ scene I
def scene1():
    p = []
    p.append(G('a-draw', 100, f'<path class="ln" d="M70 190 H1050" pathLength="100" style="stroke-width:2"/>'))
    p.append(G('a-in', 0, ICON('laptop', 18, 176, 30, 'var(--ps-color-ink)')))
    p.append(G('a-pop', 2600, ICON('flag', 1068, 176, 30, RED)))
    x0, step = 96, 73
    for i, ev in enumerate(EVENTS):
        x = x0 + i * step; d = 400 + i * 150; blk = ev in BLOCK
        col = RED if blk else BLU
        ring = f'<circle class="a-pulse" cx="{x}" cy="190" r="14" fill="none" stroke="{RED}" stroke-width="2" style="--d:{d+300}"/>' if blk else ''
        p.append(G('a-pop', d, f'<circle cx="{x}" cy="190" r="{9 if blk else 7}" fill="{col}"/>' + ring))
        # labels alternate above and below; the two loop events (4, 5) flank the loop arc so nothing crosses a label
        up = (i % 2 == 0) if i < 4 else (i in (4, 5) or i % 2 == 1)
        ly = 150 if up else 236
        anchor, lx = 'middle', x
        if i == 4: anchor, lx, ly = 'end', x - 12, 132
        if i == 5: anchor, lx, ly = 'start', x + 12, 132
        tick = f'<path class="ln" d="M{x} {190 - 11 if up else 190 + 11} V{ly + 8 if up else ly - 14}" style="stroke-width:1;opacity:.6"/>' if i not in (4, 5) else ''
        p.append(G('a-in', d + 80, tick + T(lx, ly, ev, 'm', anchor, f'style="fill:{RED if blk else "var(--ps-color-ink-2)"};font-weight:{700 if blk else 500}"')))
    # tool loop arc over preToolUse(4) .. postToolUse(5)
    xa, xb = x0 + 4 * step, x0 + 5 * step
    loop = f'M{xa} 178 C{xa} 112 {xb} 112 {xb} 178'
    p.append(G('a-in', 2900, f'<path d="{loop}" fill="none" stroke="{YEL}" stroke-width="2" stroke-dasharray="4 4"/>' + T((xa + xb) / 2, 118, 'loop', 'm', 'middle', f'style="fill:var(--ps-text-yellow)"')))
    p.append(f'<circle r="4" fill="{YEL}" opacity="0"><animate attributeName="opacity" values="0;1;1;0" keyTimes="0;.1;.9;1" dur="2.4s" begin="3.2s" repeatCount="indefinite"/><animateMotion dur="2.4s" begin="3.2s" repeatCount="indefinite" path="{loop}"/></circle>')
    # turn bracket
    xt0, xt1 = x0 + 1 * step, x0 + 7 * step
    p.append(G('a-in', 2700, f'<path class="ln" d="M{xt0} 262 V276 H{xt1} V262" style="stroke:{YEL};stroke-width:2"/>' + T((xt0 + xt1) / 2, 300, '', 'm m--b', 'middle', f'style="fill:var(--ps-text-yellow)" data-i18n="sc1.turn"')))
    xs0, xs1 = x0 + 8 * step, x0 + 12 * step
    p.append(G('a-in', 2800, f'<path class="ln" d="M{xs0} 262 V276 H{xs1} V262" style="stroke:{GRN};stroke-width:2"/>' + T((xs0 + xs1) / 2, 300, '', 'm m--b', 'middle', f'style="fill:var(--ps-text-green)" data-i18n="sc1.any"')))
    return ''.join(p)

# ------------------------------------------------------------------ scene II
def scene2():
    p = []
    p.append(G('a-in', 0, R(40, 30, 330, 250) + T(58, 56, 'stdin · JSON', 'm m--b') + ICON('json', 330, 40, 22, GRN)))
    lines = [('"event"', 120, BLU), ('"sessionId"', 150, INK3), ('"toolName": "bash"', 170, BLU), ('"toolArgs"', 130, INK3), ('  "command": "git push --force"', 240, RED), ('"cwd"', 90, INK3), ('"timestamp"', 120, INK3)]
    for i, (lab, w, col) in enumerate(lines):
        y = 78 + i * 27
        p.append(G('a-type', 300 + i * 160, f'<rect x="58" y="{y}" width="{w}" height="14" rx="3" fill="{col}" opacity=".18"/>' + T(64, y + 11, lab, 'm', 'start', f'style="fill:{col};font-size:10.5px"')))
    p.append(G('a-draw', 1150, f'<path class="ln" d="M370 155 H470" pathLength="100" marker-end="url(#sc-ar-g)" style="stroke:{GRN};stroke-width:2"/>'))
    p.append(G('a-flash', 1350, R(470, 100, 180, 110, 'var(--ps-color-paper)', GRN, 12, 'stroke-width="2"') + ICON('terminal', 545, 112, 30, GRN) + T(560, 166, 'hook', 'lbl', 'middle') + T(560, 186, 'command · 180 ms', 'm', 'middle')))
    p.append(f'<rect class="a-pulse" x="470" y="100" width="180" height="110" rx="12" fill="none" stroke="{GRN}" stroke-width="2" style="--d:1650;opacity:.5"/>')
    p.append(G('a-draw', 1850, f'<path class="ln" d="M650 155 H750" pathLength="100" marker-end="url(#sc-ar-g)" style="stroke:{GRN};stroke-width:2"/>'))
    p.append(G('a-in', 0, R(750, 30, 330, 250) + T(768, 56, 'stdout · JSON', 'm m--b') + ICON('json', 1040, 40, 22, GRN)))
    out = [('{', INK3), ('  "permissionDecision": "deny",', RED), ('  "permissionDecisionReason":', INK3), ('    "No force push to main.', 'var(--ps-color-ink)'), ('     Open a pull request."', 'var(--ps-color-ink)'), ('}', INK3)]
    for i, (lab, col) in enumerate(out):
        p.append(G('a-in', 2050 + i * 130, T(768, 86 + i * 24, lab, 'm', 'start', f'style="fill:{col}"')))
    p.append(PILL(500, 236, 120, 'exit 0', GRN, 2900))
    p.append(PILL(500, 274, 120, 'stdout → decision', BLU, 3080))
    return ''.join(p)

# ------------------------------------------------------------------ scene III
def scene3():
    p = []
    src = [('policy.d/*.json', RED, 'admin'), ('.github/hooks/*.json', BLU, 'repo'), ('~/.copilot/hooks/*.json', BLU, 'user'), ('.github/copilot/settings.json', BLU, 'repo'), ('~/.copilot/settings.json', BLU, 'user'), ('plugin hooks.json', GRN, 'plugin')]
    for i, (lab, col, who) in enumerate(src):
        y = 18 + i * 46
        p.append(G('a-slide', 200 + i * 220, R(60, y, 330, 38) + f'<rect x="60" y="{y}" width="5" height="38" rx="2" fill="{col}"/>' + T(80, y + 24, f'{i+1}', 'm m--b', 'start', f'style="fill:{col}"') + T(100, y + 24, lab, 'm', 'start', 'style="fill:var(--ps-color-ink)"') + T(380, y + 24, who, 'm', 'end', f'style="fill:{col}"')))
        p.append(G('a-draw', 600 + i * 220, f'<path class="ln" d="M390 {y+19} C520 {y+19} 560 165 690 165" pathLength="100" style="stroke:{col};opacity:.7"/>'))
    p.append(G('a-pop', 2100, f'<circle cx="690" cy="165" r="10" fill="{YEL}"/>'))
    p.append(G('a-draw', 2200, f'<path class="ln" d="M700 165 H780" pathLength="100" marker-end="url(#sc-ar-y)" style="stroke:{YEL};stroke-width:2"/>'))
    p.append(G('a-pop', 2500, R(780, 105, 300, 120, 'var(--ps-color-paper)', YEL, 12, 'stroke-width="2"') + T(930, 150, '1', 'lbl', 'middle', 'style="font-size:44px;font-family:var(--ps-font-mono);font-weight:700;fill:var(--ps-text-yellow)"') + T(930, 178, '', 'm m--b', 'middle', 'data-i18n="sc3.one"') + T(930, 200, 'entries run in order', 'm', 'middle', 'data-i18n="sc3.order"')))
    p.append(G('a-in', 3000, T(560, 322, '', 'm', 'middle', 'data-i18n="sc3.note" style="fill:var(--ps-color-ink-3)"')))
    return ''.join(p)

# ------------------------------------------------------------------ scene IV
def scene4():
    p = []
    # shield
    p.append(G('a-pop', 200, f'<circle cx="560" cy="165" r="62" fill="color-mix(in srgb, {BLU} 10%, transparent)"/>' + ICON('shield', 524, 129, 72, BLU) + T(560, 252, 'preToolUse', 'm m--b', 'middle', f'style="fill:var(--ps-text-blue)"')))
    # command 1 passes
    sg = 'style="fill:var(--ps-text-green)"'
    p.append('<g class="a-pass" style="--d:900">' + R(0, 96, 150, 30, f'color-mix(in srgb, {GRN} 16%, transparent)', GRN, 15) + T(75, 116, 'npm test', 'm m--b', 'middle', sg) + '</g>')
    p.append(G('a-pop', 3000, ICON('check', 1010, 96, 30, GRN) + T(1025, 150, 'allow', 'm m--b', 'middle', f'style="fill:var(--ps-text-green)"')))
    # command 2 bounces
    sr = 'style="fill:var(--ps-text-red);font-size:10.5px"'
    p.append('<g class="a-bounce" style="--d:3400">' + R(0, 204, 190, 30, f'color-mix(in srgb, {RED} 16%, transparent)', RED, 15) + T(95, 224, 'rm -rf / --no-preserve-root', 'm m--b', 'middle', sr) + '</g>')
    p.append(f'<circle class="a-hit" cx="560" cy="165" r="62" fill="none" stroke="{RED}" stroke-width="3" style="--d:4300"/>')
    p.append(G('a-in', 4700, R(700, 190, 380, 74, 'var(--ps-color-paper)', RED, 10) + f'<rect x="700" y="190" width="5" height="74" rx="2" fill="{RED}"/>' + T(720, 214, 'deny', 'm m--b', 'start', f'style="fill:var(--ps-text-red)"') + T(720, 234, '"Destructive delete. Use a scoped path."', 'm', 'start') + T(720, 252, 'exit 0 · reason goes back to the agent', 'm', 'start', f'style="fill:{INK3};font-size:10px"')))
    p.append(G('a-in', 5200, T(560, 312, '', 'm', 'middle', 'data-i18n="sc4.note" style="fill:var(--ps-color-ink-3)"')))
    return ''.join(p)

# ------------------------------------------------------------------ scene V
def scene5():
    p = []
    cx, cy, r = 560, 176, 98
    p.append(G('a-draw', 200, f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="none" stroke="{RED}" stroke-width="2" stroke-dasharray="6 5" pathLength="100" class="ln"/>'))
    # the traveling dot is drawn before the stations, so it passes under them and never over an icon
    p.append(f'<circle r="6" fill="{RED}" opacity="0"><animate attributeName="opacity" values="0;1;1;0" keyTimes="0;.05;.95;1" dur="4s" begin="0.6s" repeatCount="indefinite"/><animateMotion dur="4s" begin="0.6s" repeatCount="indefinite" path="M{cx} {cy-r} A{r} {r} 0 1 1 {cx-0.01} {cy-r}"/></circle>')
    nodes = [(cx, cy - r, 'agentStop', RED, 700), (cx + r, cy, 'tests?', YEL, 1500), (cx, cy + r, 'block + reason', RED, 2300), (cx - r, cy, 'npm test', GRN, 3100)]
    for x, y, a, col, d in nodes:
        p.append(G('a-pop', d, f'<circle cx="{x}" cy="{y}" r="30" fill="var(--ps-color-paper)" stroke="{col}" stroke-width="2.5"/>' + ICON({'agentStop': 'flag', 'tests?': 'test', 'block + reason': 'ban', 'npm test': 'check'}[a], x - 12, y - 12, 24, col)))
    # labels sit outside the ring with at least 12px of air from every node edge
    p.append(G('a-in', 800, T(cx, cy - r - 52, 'agentStop', 'lbl', 'middle') + T(cx, cy - r - 36, 'wants to stop', 'm', 'middle')))
    p.append(G('a-in', 1600, T(cx + r + 46, cy - 4, 'stop_hook_active = false', 'm', 'start') + T(cx + r + 46, cy + 14, 'tests not run yet', 'm m--b', 'start', f'style="fill:var(--ps-text-yellow)"')))
    p.append(G('a-in', 2400, T(cx, cy + r + 50, '{"decision":"block","reason":"Run npm test"}', 'm', 'middle', f'style="fill:var(--ps-text-red)"')))
    p.append(G('a-in', 3200, T(cx - r - 46, cy - 4, 'forced turn', 'm m--b', 'end', f'style="fill:var(--ps-text-green)"') + T(cx - r - 46, cy + 14, 'agent runs the tests', 'm', 'end')))
    p.append(G('a-pop', 4200, f'<circle cx="{cx}" cy="{cy}" r="36" fill="color-mix(in srgb, {GRN} 14%, transparent)"/>' + ICON('check', cx - 16, cy - 16, 32, GRN) + T(cx, cy + 50, 'stop ✓ · block 1/8', 'm m--b', 'middle', f'style="fill:var(--ps-text-green)"')))
    return ''.join(p)

# ------------------------------------------------------------------ scene VI
def scene6():
    p = []
    p.append(G('a-in', 0, R(40, 100, 220, 130) + ICON('laptop', 130, 118, 40, 'var(--ps-color-ink)') + T(150, 190, 'GitHub Copilot CLI', 'lbl', 'middle') + T(150, 210, 'hooks run here', 'm', 'middle')))
    lanes = [(60, 'SIEM · Log Analytics', 'cloud', GRN, 'http hook', 'hook.end · deny · session id'), (165, 'OpenTelemetry', 'chart', BLU, 'span events', 'hook.start · hook.end · traceparent'), (270, 'GitHub audit log', 'shield', YEL, 'platform', 'agent_session.* · no local prompts')]
    for i, (y, lab, icn, col, tag, sub) in enumerate(lanes):
        d = 400 + i * 350
        dash = ' stroke-dasharray="5 5"' if i == 2 else ''
        p.append(G('a-draw', d, f'<path class="ln" d="M260 165 C420 165 420 {y} 560 {y} H820" pathLength="100" style="stroke:{col};stroke-width:2"{dash}/>'))
        p.append(G('a-in', d + 300, T(690, y - 24, tag, 'm m--b', 'middle', f'style="fill:{col}"')))
        p.append(G('a-pop', d + 500, R(820, y - 36, 300, 72) + f'<rect x="820" y="{y-36}" width="5" height="72" rx="2" fill="{col}"/>' + ICON(icn, 838, y - 14, 28, col) + T(878, y - 6, lab, 'lbl') + T(878, y + 14, sub, 'm', 'start', 'style="font-size:10px"')))
        if i < 2:
            for k in range(3):
                p.append(f'<rect width="18" height="10" rx="2" fill="{col}" opacity="0"><animate attributeName="opacity" values="0;1;1;0" keyTimes="0;.08;.92;1" dur="3s" begin="{2 + k + i * 0.4}s" repeatCount="indefinite"/><animateMotion dur="3s" begin="{2 + k + i * 0.4}s" repeatCount="indefinite" path="M251 160 C411 160 411 {y-5} 551 {y-5} H811"/></rect>')
    p.append(G('a-in', 1900, R(560, 292, 250, 26, f'color-mix(in srgb, {RED} 14%, transparent)', RED, 13) + T(685, 309, 'not captured: local prompts, args', 'm m--b', 'middle', f'style="fill:var(--ps-text-red);font-size:10.5px"')))
    return ''.join(p)

# ------------------------------------------------------------------ scene VII
def scene7():
    p = []
    rows = [('~/.copilot/hooks', 'user', True), ('.github/hooks', 'repo', True), ('settings.json', 'inline', True), ('policy.d · managed', 'admin', False)]
    for i, (lab, who, off) in enumerate(rows):
        y = 30 + i * 66; d = 300 + i * 600
        col = RED if not off else BLU
        p.append(G('a-in', 100 + i * 120, R(60, y, 560, 50) + f'<rect x="60" y="{y}" width="5" height="50" rx="2" fill="{col}"/>' + T(84, y + 31, lab, 'lbl') + T(300, y + 31, who, 'm', 'start', f'style="fill:{INK3}"')))
        if off:
            p.append(G('a-in', 100 + i * 120, f'<rect x="440" y="{y+14}" width="52" height="24" rx="12" fill="{GRN}" opacity=".85"/>' + f'<circle class="a-flip" cx="479" cy="{y+26}" r="9" fill="#fff" style="--d:{d}"/>'))
            p.append(G('a-in', d + 400, T(506, y + 31, 'off', 'm m--b', 'start', f'style="fill:{INK3}"')))
            p.append(f'<rect class="a-in" x="440" y="{y+14}" width="52" height="24" rx="12" fill="{INK3}" opacity=".35" style="--d:{d+200}"/>')
        else:
            p.append(G('a-in', 100 + i * 120, f'<rect x="440" y="{y+14}" width="52" height="24" rx="12" fill="{RED}"/><circle cx="479" cy="{y+26}" r="9" fill="#fff"/>'))
            p.append(G('a-in', 2900, T(506, y + 31, 'on', 'm m--b', 'start', f'style="fill:var(--ps-text-red)"')))
            p.append(G('a-shake', 2500, ICON('lock', 560, y + 12, 26, RED)))
    p.append(G('a-in', 2000, R(660, 60, 420, 200, 'var(--ps-color-paper)', RED, 12, 'stroke-width="2"') + ICON('lock', 680, 78, 26, RED) + T(716, 97, 'managed settings', 'lbl') + T(680, 130, '"allowManagedHooksOnly": true', 'm', 'start', f'style="fill:var(--ps-text-red)"') + T(680, 152, '"disableBypassPermissionsMode": "disable"', 'm') + T(680, 174, '"permissions": { "deny": ["Shell(rm -rf *)"] }', 'm') + T(680, 210, '', 'm m--b', 'start', 'data-i18n="sc7.who"') + T(680, 232, '', 'm', 'start', 'data-i18n="sc7.how" style="fill:var(--ps-color-ink-3)"')))
    p.append(G('a-in', 3400, T(560, 312, '', 'm', 'middle', 'data-i18n="sc7.note" style="fill:var(--ps-color-ink-3)"')))
    return ''.join(p)

# ------------------------------------------------------------------ scene VIII
def scene8():
    p = []
    steps = [('observe', 'week 1', 'eye', BLU), ('protect', 'weeks 2 to 4', 'shield', GRN), ('automate', 'month 2', 'wrench', YEL), ('govern', 'month 3', 'lock', RED)]
    base = 300; W = 236; X0 = 70; GAP = 250
    for i, (lab, when, icn, col) in enumerate(steps):
        x = X0 + i * GAP; hh = 60 + i * 54; y = base - hh; d = 300 + i * 500
        p.append(G('a-rise', d, R(x, y, W, hh, f'color-mix(in srgb, {col} 12%, transparent)', col, 10, 'stroke-width="1.5"') + f'<rect x="{x}" y="{y}" width="{W}" height="6" rx="3" fill="{col}"/>' + ICON(icn, x + 16, y + 20, 28, col) + T(x + 56, y + 32, '', 'lbl', 'start', f'data-i18n="sc8.s{i+1}"') + T(x + 56, y + 52, '', 'm', 'start', f'data-i18n="sc8.w{i+1}" style="fill:{INK3};font-size:10px"') + T(x + W - 12, y + hh - 12, f'{i+1}', 'm', 'end', f'style="fill:{col};font-size:30px;font-weight:700;opacity:.35"')))
    p.append(G('a-draw', 400, f'<path class="ln" d="M40 {base+6} H1080" pathLength="100" style="stroke-width:2"/>'))
    # climbing dot: rises to 16px above each step, runs along the top, ends over the middle of the last step
    pts = [f'M40 {base-16}']
    for i in range(4):
        x = X0 + i * GAP; y = base - (60 + i * 54) - 16
        pts.append(f'L{x + 12} {y} L{x + (W // 2 if i == 3 else W - 12)} {y}')
    p.append(f'<circle r="8" fill="{RED}" opacity="0"><animate attributeName="opacity" values="0;1;1;1" keyTimes="0;.1;.9;1" dur="4.4s" begin="0.8s" fill="freeze"/><animateMotion dur="4.4s" begin="0.8s" fill="freeze" path="{" ".join(pts)}"/></circle>')
    x4 = X0 + 3 * GAP; y4 = base - (60 + 3 * 54)
    # the goal sits above the last step, right-aligned to its edge, so a longer language never leaves the canvas
    p.append(G('a-pop', 5400, ICON('flag', x4 + W - 34, y4 - 56, 26, RED) + T(x4 + W - 44, y4 - 36, '', 'm m--b', 'end', 'data-i18n="sc8.goal" style="fill:var(--ps-text-red)"')))
    return ''.join(p)

MARKER = '<defs>' + ''.join(f'<marker id="sc-ar{s}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="{c}"/></marker>' for s, c in [('', INK3), ('-g', GRN), ('-y', YEL), ('-r', RED), ('-b', BLU)]) + '</defs>'
EXTRA_CSS = """
<style>
.slide[data-active="true"] .scn .a-pass { opacity: 1; animation: scPass 2.2s cubic-bezier(.4,0,.2,1) calc(var(--d, 0) * 1ms) both; }
@keyframes scPass { 0% { transform: translateX(60px); opacity: 0; } 12% { opacity: 1; } 100% { transform: translateX(910px); opacity: 1; } }
.slide[data-active="true"] .scn .a-bounce { opacity: 1; animation: scBounce 2s cubic-bezier(.4,0,.2,1) calc(var(--d, 0) * 1ms) both; }
@keyframes scBounce { 0% { transform: translateX(60px); opacity: 0; } 10% { opacity: 1; } 45% { transform: translateX(330px); } 60% { transform: translateX(255px); } 100% { transform: translateX(265px); opacity: 1; } }
.slide[data-active="true"] .scn .a-hit { animation: scHit 1s ease calc(var(--d, 0) * 1ms) both; }
@keyframes scHit { 0% { opacity: 0; } 20% { opacity: 1; } 100% { opacity: .35; } }
.scene-slide .title { max-width: 1180px; }
</style>
"""

SCENES = {
 1: dict(fn=scene1, accent='red', eyebrow={'en': 'Scene · the lifecycle', 'pt-BR': 'Cena · o ciclo de vida', 'es': 'Escena · el ciclo de vida'},
    title={'en': 'One session, in the order the runtime fires it.', 'pt-BR': 'Uma sessão, na ordem em que o runtime dispara.', 'es': 'Una sesión, en el orden en que el runtime dispara.'},
    keys={'turn': {'en': 'the turn: repeats per prompt', 'pt-BR': 'o turno: repete a cada prompt', 'es': 'el turno: se repite por prompt'}, 'any': {'en': 'anywhere in the session', 'pt-BR': 'em qualquer ponto da sessão', 'es': 'en cualquier punto de la sesión'}},
    caps=[('red', {'en': ('Three decide', 'permissionRequest, preToolUse and agentStop are the only events that can say no. The other eleven observe, inject or notify.'), 'pt-BR': ('Três decidem', 'permissionRequest, preToolUse e agentStop são os únicos eventos que podem dizer não. Os outros onze observam, injetam ou notificam.'), 'es': ('Tres deciden', 'permissionRequest, preToolUse y agentStop son los únicos eventos que pueden decir no. Los otros once observan, inyectan o notifican.')}),
          ('yellow', {'en': ('The loop is per tool call', 'preToolUse and postToolUse repeat for every command, edit or MCP call inside the turn; a slow hook is paid every time.'), 'pt-BR': ('O loop é por chamada de tool', 'preToolUse e postToolUse repetem a cada comando, edição ou chamada MCP dentro do turno; um hook lento é pago toda vez.'), 'es': ('El loop es por llamada de tool', 'preToolUse y postToolUse se repiten en cada comando, edición o llamada MCP dentro del turno; un hook lento se paga cada vez.')}),
          ('green', {'en': ('Five fire anywhere', 'Subagents, compaction, errors and notifications are not tied to the turn. Design their hooks as observers, never as gates.'), 'pt-BR': ('Cinco disparam em qualquer lugar', 'Subagentes, compactação, erros e notificações não dependem do turno. Desenhe esses hooks como observadores, nunca como gates.'), 'es': ('Cinco disparan en cualquier lugar', 'Subagentes, compactación, errores y notificaciones no dependen del turno. Diseñe esos hooks como observadores, nunca como gates.')})],
    notes={'en': "**[OPENING]**\nWatch the line fill in. Fourteen moments, one after the other, and the runtime never skips one.\n\n**[CORE]**\nThe red dots are the only three that decide. Everything else is a window: you see the payload, you can add context, you can ship it somewhere, but you cannot stop the run. The yellow loop over preToolUse and postToolUse is where cost lives: it repeats for every tool call, so a guardrail that takes two seconds turns a ten-call turn into twenty seconds of waiting. The green bracket is the set that fires anywhere: subagents, compaction, errors, notifications.\n\n**[PROVOCATIVE HOOK]**\nIf your guardrail is not on one of the three red dots, is it a guardrail, or is it a log line?\n\n**[TRANSITION, to the next slide]**\nNow the same fourteen, drawn as zones, with the surfaces that support each one.\n\n**[TIMING]** ~2 min",
           'pt-BR': "**[ABERTURA]**\nOlha a linha se preencher. Catorze momentos, um depois do outro, e o runtime nunca pula nenhum.\n\n**[NÚCLEO]**\nOs pontos vermelhos são os únicos três que decidem. Todo o resto é janela: você vê o payload, pode acrescentar contexto, pode mandar para fora, mas não consegue parar a execução. O loop amarelo sobre preToolUse e postToolUse é onde mora o custo: ele repete a cada chamada de tool, então um guardrail que leva dois segundos transforma um turno de dez chamadas em vinte segundos de espera. O colchete verde é o conjunto que dispara em qualquer lugar: subagentes, compactação, erros, notificações.\n\n**[GANCHO PROVOCATIVO]**\nSe o seu guardrail não está em um dos três pontos vermelhos, ele é um guardrail, ou é uma linha de log?\n\n**[TRANSIÇÃO, para o próximo slide]**\nAgora os mesmos catorze, desenhados em zonas, com as superfícies que suportam cada um.\n\n**[TIMING]** ~2 min",
           'es': "**[APERTURA]**\nMiren la línea llenarse. Catorce momentos, uno tras otro, y el runtime nunca se salta ninguno.\n\n**[NÚCLEO]**\nLos puntos rojos son los únicos tres que deciden. Todo lo demás es una ventana: ven el payload, pueden agregar contexto, pueden enviarlo afuera, pero no pueden detener la ejecución. El loop amarillo sobre preToolUse y postToolUse es donde vive el costo: se repite en cada llamada de tool, así que un guardrail de dos segundos convierte un turno de diez llamadas en veinte segundos de espera. El corchete verde es el conjunto que dispara en cualquier lugar: subagentes, compactación, errores, notificaciones.\n\n**[GANCHO PROVOCATIVO]**\nSi su guardrail no está en uno de los tres puntos rojos, ¿es un guardrail o es una línea de log?\n\n**[TRANSICIÓN, al siguiente slide]**\nAhora los mismos catorce, dibujados en zonas, con las superficies que soportan cada uno.\n\n**[TIMING]** ~2 min"}),
 2: dict(fn=scene2, accent='green', eyebrow={'en': 'Scene · the contract', 'pt-BR': 'Cena · o contrato', 'es': 'Escena · el contrato'},
    title={'en': 'A payload goes in on stdin. A decision comes out on stdout.', 'pt-BR': 'Um payload entra pelo stdin. Uma decisão sai pelo stdout.', 'es': 'Un payload entra por stdin. Una decisión sale por stdout.'},
    keys={},
    caps=[('green', {'en': ('stdin is the whole story', 'Event, session id, tool name and the raw toolArgs string arrive as one JSON object. Parse it twice: the object, then the command inside.'), 'pt-BR': ('O stdin é a história inteira', 'Evento, id da sessão, nome da tool e a string crua de toolArgs chegam como um único JSON. Faça o parse duas vezes: o objeto, depois o comando dentro dele.'), 'es': ('stdin es toda la historia', 'Evento, id de sesión, nombre de la tool y la cadena cruda de toolArgs llegan como un solo JSON. Parsee dos veces: el objeto y luego el comando adentro.')}),
          ('blue', {'en': ('stdout is the decision', 'One JSON object, nothing else. permissionDecision plus a reason the agent can act on; progress lines are stripped, two objects are ignored.'), 'pt-BR': ('O stdout é a decisão', 'Um único objeto JSON, nada mais. permissionDecision mais um motivo que o agente consegue usar; linhas de progresso são removidas, dois objetos são ignorados.'), 'es': ('stdout es la decisión', 'Un solo objeto JSON, nada más. permissionDecision más un motivo que el agente pueda usar; las líneas de progreso se eliminan, dos objetos se ignoran.')}),
          ('yellow', {'en': ('Exit codes carry meaning', 'Exit 0 parses stdout; exit 2 is a deny on the gates; other errors fail open, except preToolUse. Timeouts always fail open.'), 'pt-BR': ('Exit codes carregam significado', 'Exit 0 faz o parse do stdout; exit 2 é deny nos gates; outros erros são fail-open, exceto no preToolUse. Timeout é sempre fail-open.'), 'es': ('Los exit codes significan algo', 'Exit 0 parsea stdout; exit 2 es deny en los gates; otros errores son fail-open, salvo en preToolUse. El timeout siempre es fail-open.')})],
    notes={'en': "**[OPENING]**\nEvery hook you will ever write is this picture. Left in, right out, one process in the middle.\n\n**[CORE]**\nThe left card is the payload: it types in line by line because that is how you should read it, field by field. Notice the command line in red: it is a string inside a string, which is why half of the broken hooks in the wild forgot the second parse. The box in the middle is your script, with a timeout of thirty seconds by default. The right card is the only thing the runtime reads back: one JSON object with a decision and a reason. The reason is not for the log; it goes back to the model as the next instruction.\n\n**[PROVOCATIVE HOOK]**\nWhat does your hook say when it denies? If the answer is nothing, the agent will retry the same command with a different flag.\n\n**[TRANSITION, to the next slide]**\nThe configuration file that wires this contract to each event.\n\n**[TIMING]** ~2 min",
           'pt-BR': "**[ABERTURA]**\nTodo hook que você vai escrever é este desenho. Entra pela esquerda, sai pela direita, um processo no meio.\n\n**[NÚCLEO]**\nO card da esquerda é o payload: ele aparece linha a linha porque é assim que você deveria lê-lo, campo a campo. Repare na linha do comando em vermelho: é uma string dentro de uma string, e é por isso que metade dos hooks quebrados por aí esqueceu o segundo parse. A caixa do meio é o seu script, com timeout de trinta segundos por padrão. O card da direita é a única coisa que o runtime lê de volta: um objeto JSON com decisão e motivo. O motivo não é para o log; ele volta para o modelo como a próxima instrução.\n\n**[GANCHO PROVOCATIVO]**\nO que o seu hook diz quando nega? Se a resposta é nada, o agente vai tentar o mesmo comando com outra flag.\n\n**[TRANSIÇÃO, para o próximo slide]**\nO arquivo de configuração que liga este contrato a cada evento.\n\n**[TIMING]** ~2 min",
           'es': "**[APERTURA]**\nTodo hook que vayan a escribir es este dibujo. Entra por la izquierda, sale por la derecha, un proceso en el medio.\n\n**[NÚCLEO]**\nLa tarjeta de la izquierda es el payload: aparece línea por línea porque así deberían leerlo, campo por campo. Fíjense en la línea del comando en rojo: es una cadena dentro de una cadena, y por eso la mitad de los hooks rotos olvidó el segundo parse. La caja del medio es su script, con timeout de treinta segundos por defecto. La tarjeta de la derecha es lo único que el runtime lee de vuelta: un objeto JSON con decisión y motivo. El motivo no es para el log; vuelve al modelo como la próxima instrucción.\n\n**[GANCHO PROVOCATIVO]**\n¿Qué dice su hook cuando niega? Si la respuesta es nada, el agente reintentará el mismo comando con otra flag.\n\n**[TRANSICIÓN, al siguiente slide]**\nEl archivo de configuración que conecta este contrato con cada evento.\n\n**[TIMING]** ~2 min"}),
 3: dict(fn=scene3, accent='yellow', eyebrow={'en': 'Scene · the sources', 'pt-BR': 'Cena · as fontes', 'es': 'Escena · las fuentes'},
    title={'en': 'Six files, one merged configuration, always in this order.', 'pt-BR': 'Seis arquivos, uma configuração mesclada, sempre nesta ordem.', 'es': 'Seis archivos, una configuración fusionada, siempre en este orden.'},
    keys={'one': {'en': 'one hook set', 'pt-BR': 'um conjunto de hooks', 'es': 'un conjunto de hooks'}, 'order': {'en': 'entries run in load order', 'pt-BR': 'entradas rodam na ordem de carga', 'es': 'las entradas corren en orden de carga'}, 'note': {'en': 'nothing replaces anything: every entry of every source runs', 'pt-BR': 'nada substitui nada: toda entrada de toda fonte roda', 'es': 'nada reemplaza nada: toda entrada de toda fuente corre'}},
    caps=[('red', {'en': ('Policy loads first', 'policy.d and the registry are root-owned, load before trust is evaluated and ignore disableAllHooks. That is the admin lane.'), 'pt-BR': ('Policy carrega primeiro', 'policy.d e o registro são de dono root, carregam antes da avaliação de trust e ignoram disableAllHooks. Essa é a faixa do admin.'), 'es': ('Policy carga primero', 'policy.d y el registro son de root, cargan antes de evaluar trust e ignoran disableAllHooks. Ese es el carril del admin.')}),
          ('blue', {'en': ('Repo and user merge', '.github/hooks, ~/.copilot/hooks and the two settings.json all contribute; the repository overrides the user per key, nothing is replaced wholesale.'), 'pt-BR': ('Repo e usuário se mesclam', '.github/hooks, ~/.copilot/hooks e os dois settings.json contribuem; o repositório sobrescreve o usuário por chave, nada é substituído em bloco.'), 'es': ('Repo y usuario se fusionan', '.github/hooks, ~/.copilot/hooks y los dos settings.json contribuyen; el repositorio sobreescribe al usuario por clave, nada se reemplaza en bloque.')}),
          ('green', {'en': ('Plugins close the list', 'Plugin hooks load last and can be forced or blocked by managed settings. The cloud agent reads only the repository file.'), 'pt-BR': ('Plugins fecham a lista', 'Hooks de plugin carregam por último e podem ser forçados ou bloqueados pelos managed settings. O cloud agent lê só o arquivo do repositório.'), 'es': ('Los plugins cierran la lista', 'Los hooks de plugin cargan al final y los managed settings pueden forzarlos o bloquearlos. El cloud agent lee solo el archivo del repositorio.')})],
    notes={'en': "**[OPENING]**\nSix cards slide in, in the order the runtime reads them, and they all end in the same place.\n\n**[CORE]**\nThe mental model people get wrong: they think the last file wins. It does not. Every entry of every source runs; the order only decides who runs first and who can override a key in the inline settings. The red lane, policy, is the one the developer cannot touch and the one that ignores the kill switch. The blue lanes belong to the repository and the user, which is where ninety percent of your hooks will live. The green lane, plugins, is how you package a guardrail with the tools it protects.\n\n**[PROVOCATIVE HOOK]**\nIf a developer runs copilot in a folder they did not trust yet, which of these six still load? Only the red one.\n\n**[TRANSITION, to the next slide]**\nThe load-order diagram with paths, owners and the managed-settings gate.\n\n**[TIMING]** ~1.5 min",
           'pt-BR': "**[ABERTURA]**\nSeis cards entram, na ordem em que o runtime os lê, e todos terminam no mesmo lugar.\n\n**[NÚCLEO]**\nO modelo mental que as pessoas erram: acham que o último arquivo vence. Não vence. Toda entrada de toda fonte roda; a ordem só decide quem roda primeiro e quem sobrescreve uma chave nos settings inline. A faixa vermelha, policy, é a que o desenvolvedor não toca e a que ignora o botão de desligar. As faixas azuis são do repositório e do usuário, onde noventa por cento dos seus hooks vão viver. A faixa verde, plugins, é como você empacota um guardrail junto com as tools que ele protege.\n\n**[GANCHO PROVOCATIVO]**\nSe um desenvolvedor roda copilot numa pasta que ainda não confiou, quais destas seis ainda carregam? Só a vermelha.\n\n**[TRANSIÇÃO, para o próximo slide]**\nO diagrama de ordem de carga com caminhos, donos e o gate dos managed settings.\n\n**[TIMING]** ~1.5 min",
           'es': "**[APERTURA]**\nSeis tarjetas entran, en el orden en que el runtime las lee, y todas terminan en el mismo lugar.\n\n**[NÚCLEO]**\nEl modelo mental que la gente se equivoca: creen que el último archivo gana. No gana. Toda entrada de toda fuente corre; el orden solo decide quién corre primero y quién sobreescribe una clave en los settings inline. El carril rojo, policy, es el que el desarrollador no toca y el que ignora el interruptor de apagado. Los carriles azules son del repositorio y del usuario, donde vivirá el noventa por ciento de sus hooks. El carril verde, plugins, es cómo empaquetan un guardrail junto con las tools que protege.\n\n**[GANCHO PROVOCATIVO]**\nSi un desarrollador corre copilot en una carpeta que aún no confió, ¿cuáles de estas seis cargan? Solo la roja.\n\n**[TRANSICIÓN, al siguiente slide]**\nEl diagrama de orden de carga con rutas, dueños y la puerta de los managed settings.\n\n**[TIMING]** ~1.5 min"}),
 4: dict(fn=scene4, accent='blue', eyebrow={'en': 'Scene · the gate', 'pt-BR': 'Cena · o gate', 'es': 'Escena · el gate'},
    title={'en': 'Two commands reach preToolUse. One passes. One comes back with a reason.', 'pt-BR': 'Dois comandos chegam ao preToolUse. Um passa. Um volta com um motivo.', 'es': 'Dos comandos llegan a preToolUse. Uno pasa. Uno vuelve con un motivo.'},
    keys={'note': {'en': 'the reason is written for the agent, not for the log', 'pt-BR': 'o motivo é escrito para o agente, não para o log', 'es': 'el motivo se escribe para el agente, no para el log'}},
    caps=[('green', {'en': ('allow is silent', 'npm test matches nothing in the deny list; the hook exits 0 with allow and the runtime moves on to the permission service.'), 'pt-BR': ('allow é silencioso', 'npm test não casa com nada na deny list; o hook sai com 0 e allow, e o runtime segue para o serviço de permissão.'), 'es': ('allow es silencioso', 'npm test no coincide con nada en la deny list; el hook sale con 0 y allow, y el runtime sigue al servicio de permisos.')}),
          ('red', {'en': ('deny bounces with a reason', 'The destructive delete never runs. The reason goes back to the model as the next instruction, so it proposes a scoped path instead of retrying.'), 'pt-BR': ('deny volta com um motivo', 'O delete destrutivo nunca roda. O motivo volta para o modelo como a próxima instrução, então ele propõe um caminho restrito em vez de tentar de novo.'), 'es': ('deny rebota con un motivo', 'El borrado destructivo nunca corre. El motivo vuelve al modelo como la próxima instrucción, así propone una ruta acotada en vez de reintentar.')}),
          ('blue', {'en': ('preToolUse is fail-closed', 'A crashed hook here denies the tool; a timeout does not. Keep the script local, under a second, and free of network calls.'), 'pt-BR': ('preToolUse é fail-closed', 'Um hook que quebra aqui nega a tool; um timeout não. Mantenha o script local, abaixo de um segundo e sem chamadas de rede.'), 'es': ('preToolUse es fail-closed', 'Un hook que se rompe aquí niega la tool; un timeout no. Mantengan el script local, por debajo de un segundo y sin llamadas de red.')})],
    notes={'en': "**[OPENING]**\nSame gate, two commands, and the difference is one line of reason.\n\n**[CORE]**\nThe green pill goes straight through: the hook found nothing to object to and said allow, which is the boring, correct default. The red pill hits the shield and comes back. What comes back with it matters more than the deny itself: a reason the model can act on. Write it as an instruction, not as an error message. 'Destructive delete. Use a scoped path.' produces a scoped path on the next turn; 'blocked by policy' produces a retry with a different flag. Last point: this gate is the only fail-closed one. If your script crashes here, the tool is denied; if it times out, the tool runs.\n\n**[PROVOCATIVE HOOK]**\nRead your last deny message out loud. Would you know what to do next?\n\n**[TRANSITION, to the next slide]**\nThe full chain: permissionRequest, the permission service, preToolUse, the sandbox.\n\n**[TIMING]** ~2 min",
           'pt-BR': "**[ABERTURA]**\nMesmo gate, dois comandos, e a diferença é uma linha de motivo.\n\n**[NÚCLEO]**\nA pílula verde passa direto: o hook não achou nada para objetar e disse allow, que é o padrão chato e correto. A pílula vermelha bate no escudo e volta. O que volta com ela importa mais do que o deny em si: um motivo que o modelo consegue usar. Escreva como instrução, não como mensagem de erro. 'Delete destrutivo. Use um caminho restrito.' produz um caminho restrito no próximo turno; 'bloqueado pela política' produz uma nova tentativa com outra flag. Último ponto: este gate é o único fail-closed. Se o seu script quebra aqui, a tool é negada; se dá timeout, a tool roda.\n\n**[GANCHO PROVOCATIVO]**\nLeia em voz alta a sua última mensagem de deny. Você saberia o que fazer em seguida?\n\n**[TRANSIÇÃO, para o próximo slide]**\nA cadeia completa: permissionRequest, o serviço de permissão, preToolUse, o sandbox.\n\n**[TIMING]** ~2 min",
           'es': "**[APERTURA]**\nMismo gate, dos comandos, y la diferencia es una línea de motivo.\n\n**[NÚCLEO]**\nLa píldora verde pasa directo: el hook no encontró nada que objetar y dijo allow, que es el default aburrido y correcto. La píldora roja golpea el escudo y vuelve. Lo que vuelve con ella importa más que el deny en sí: un motivo que el modelo pueda usar. Escríbanlo como instrucción, no como mensaje de error. 'Borrado destructivo. Use una ruta acotada.' produce una ruta acotada en el siguiente turno; 'bloqueado por política' produce un reintento con otra flag. Último punto: este gate es el único fail-closed. Si su script se rompe aquí, la tool se niega; si hace timeout, la tool corre.\n\n**[GANCHO PROVOCATIVO]**\nLean en voz alta su último mensaje de deny. ¿Sabrían qué hacer después?\n\n**[TRANSICIÓN, al siguiente slide]**\nLa cadena completa: permissionRequest, el servicio de permisos, preToolUse, el sandbox.\n\n**[TIMING]** ~2 min"}),
 5: dict(fn=scene5, accent='red', eyebrow={'en': 'Scene · the finish line', 'pt-BR': 'Cena · a linha de chegada', 'es': 'Escena · la línea de llegada'},
    title={'en': 'The agent wants to stop. The hook says: not before the tests.', 'pt-BR': 'O agente quer parar. O hook diz: não antes dos testes.', 'es': 'El agente quiere parar. El hook dice: no antes de los tests.'},
    keys={},
    caps=[('red', {'en': ('block forces one more turn', 'agentStop returns decision block with a reason; the runtime starts a new turn with that reason as the prompt. Eight blocks maximum.'), 'pt-BR': ('block força mais um turno', 'agentStop devolve decision block com um motivo; o runtime inicia um novo turno com esse motivo como prompt. Oito blocks no máximo.'), 'es': ('block fuerza un turno más', 'agentStop devuelve decision block con un motivo; el runtime inicia un nuevo turno con ese motivo como prompt. Ocho blocks como máximo.')}),
          ('yellow', {'en': ('stop_hook_active is the memory', 'On the forced turn the flag is true. Check it first, or your hook blocks the same stop forever and the CLI ends the turn anyway.'), 'pt-BR': ('stop_hook_active é a memória', 'No turno forçado a flag vem true. Cheque isso primeiro, ou o hook bloqueia o mesmo stop para sempre e o CLI encerra o turno mesmo assim.'), 'es': ('stop_hook_active es la memoria', 'En el turno forzado la flag viene true. Revísenla primero, o el hook bloquea el mismo stop para siempre y el CLI termina el turno igual.')}),
          ('green', {'en': ('Proof, then stop', 'The hook reads the test log, not the model. When the log says pass, decision allow, and the session ends with evidence.'), 'pt-BR': ('Prova, depois para', 'O hook lê o log dos testes, não o modelo. Quando o log diz pass, decision allow, e a sessão termina com evidência.'), 'es': ('Prueba, luego parar', 'El hook lee el log de tests, no al modelo. Cuando el log dice pass, decision allow, y la sesión termina con evidencia.')})],
    notes={'en': "**[OPENING]**\nA circle, because that is what this event is: a loop the agent cannot leave until your hook is satisfied.\n\n**[CORE]**\nTop: the agent wants to stop. Right: the hook checks whether tests ran, from the log on disk, never from what the model claims. They did not, so the hook returns block with a reason, and the runtime starts a forced turn with that reason as the prompt. Left: the agent runs npm test. Back to the top, and now stop_hook_active is true and the log says pass, so the hook allows and the run ends. Eight blocks is the ceiling; after that the CLI ends the turn on its own, which is the runaway guard.\n\n**[PROVOCATIVE HOOK]**\nHow many of your pull requests today say 'tests pass' because the model said so?\n\n**[TRANSITION, to the next slide]**\nThe postToolUse patterns that keep the code clean while the turn runs.\n\n**[TIMING]** ~2 min",
           'pt-BR': "**[ABERTURA]**\nUm círculo, porque é isso que esse evento é: um loop do qual o agente não sai até o seu hook ficar satisfeito.\n\n**[NÚCLEO]**\nEm cima: o agente quer parar. À direita: o hook confere se os testes rodaram, pelo log em disco, nunca pelo que o modelo afirma. Não rodaram, então o hook devolve block com um motivo, e o runtime inicia um turno forçado com esse motivo como prompt. À esquerda: o agente roda npm test. De volta ao topo, e agora stop_hook_active é true e o log diz pass, então o hook libera e a execução termina. Oito blocks é o teto; depois disso o CLI encerra o turno sozinho, que é a trava contra loop infinito.\n\n**[GANCHO PROVOCATIVO]**\nQuantos dos seus pull requests de hoje dizem 'testes passam' porque o modelo disse?\n\n**[TRANSIÇÃO, para o próximo slide]**\nOs padrões de postToolUse que mantêm o código limpo enquanto o turno roda.\n\n**[TIMING]** ~2 min",
           'es': "**[APERTURA]**\nUn círculo, porque eso es este evento: un loop del que el agente no sale hasta que su hook queda satisfecho.\n\n**[NÚCLEO]**\nArriba: el agente quiere parar. A la derecha: el hook revisa si los tests corrieron, desde el log en disco, nunca desde lo que el modelo afirma. No corrieron, así que el hook devuelve block con un motivo, y el runtime inicia un turno forzado con ese motivo como prompt. A la izquierda: el agente corre npm test. De vuelta arriba, y ahora stop_hook_active es true y el log dice pass, así que el hook permite y la ejecución termina. Ocho blocks es el techo; después el CLI termina el turno solo, que es la traba contra loops infinitos.\n\n**[GANCHO PROVOCATIVO]**\n¿Cuántos de sus pull requests de hoy dicen 'los tests pasan' porque el modelo lo dijo?\n\n**[TRANSICIÓN, al siguiente slide]**\nLos patrones de postToolUse que mantienen el código limpio mientras corre el turno.\n\n**[TIMING]** ~2 min"}),
 6: dict(fn=scene6, accent='green', eyebrow={'en': 'Scene · evidence', 'pt-BR': 'Cena · evidência', 'es': 'Escena · evidencia'},
    title={'en': 'What leaves the laptop, by which door, and what never does.', 'pt-BR': 'O que sai do laptop, por qual porta, e o que nunca sai.', 'es': 'Qué sale del laptop, por qué puerta, y qué nunca sale.'},
    keys={},
    caps=[('green', {'en': ('The http hook is the SIEM door', 'A POST per event with the session id, the decision and the redacted command. Only https, headers from allowedEnvVars, five second timeout.'), 'pt-BR': ('O hook http é a porta do SIEM', 'Um POST por evento com o id da sessão, a decisão e o comando redigido. Só https, headers vindos de allowedEnvVars, timeout de cinco segundos.'), 'es': ('El hook http es la puerta del SIEM', 'Un POST por evento con el id de sesión, la decisión y el comando redactado. Solo https, headers desde allowedEnvVars, timeout de cinco segundos.')}),
          ('blue', {'en': ('Spans prove the guardrail ran', 'hook.start, hook.end and hook.error ride the session trace with traceparent; one query answers whether the deny fired and how long it took.'), 'pt-BR': ('Spans provam que o guardrail rodou', 'hook.start, hook.end e hook.error viajam no trace da sessão com traceparent; uma query responde se o deny disparou e quanto demorou.'), 'es': ('Los spans prueban que el guardrail corrió', 'hook.start, hook.end y hook.error viajan en el trace de la sesión con traceparent; una query responde si el deny disparó y cuánto tardó.')}),
          ('yellow', {'en': ('The audit log is not enough', 'GitHub records agent sessions and actors, never local prompts or arguments. If the evidence has to include the command, a hook has to ship it.'), 'pt-BR': ('O audit log não basta', 'O GitHub registra sessões e atores do agente, nunca prompts ou argumentos locais. Se a evidência precisa incluir o comando, um hook tem que enviá-la.'), 'es': ('El audit log no alcanza', 'GitHub registra sesiones y actores del agente, nunca prompts ni argumentos locales. Si la evidencia debe incluir el comando, un hook tiene que enviarla.')})],
    notes={'en': "**[OPENING]**\nThree doors out of the laptop. Two of them you build; one the platform gives you, and it is the narrowest.\n\n**[CORE]**\nThe green lane is the http hook: every event becomes a POST to your SIEM with the session id, the decision and a redacted command. The packets you see moving are those events. The blue lane is OpenTelemetry: every hook is a span on the session trace, which is how you prove, months later, that the guardrail ran on that Tuesday. The yellow lane is dashed on purpose: the GitHub audit log records that an agent session existed and who started it, but never the local prompt or the arguments. The red tag is the sentence to repeat in every compliance meeting.\n\n**[PROVOCATIVE HOOK]**\nIf an auditor asks what the agent ran on a laptop last month, which lane answers?\n\n**[TRANSITION, to the next slide]**\nThe evidence pipeline diagram with where each artifact lands.\n\n**[TIMING]** ~1.5 min",
           'pt-BR': "**[ABERTURA]**\nTrês portas para fora do laptop. Duas você constrói; uma a plataforma dá, e é a mais estreita.\n\n**[NÚCLEO]**\nA faixa verde é o hook http: cada evento vira um POST para o seu SIEM com o id da sessão, a decisão e um comando redigido. Os pacotes que você vê andando são esses eventos. A faixa azul é o OpenTelemetry: cada hook é um span no trace da sessão, e é assim que você prova, meses depois, que o guardrail rodou naquela terça. A faixa amarela é tracejada de propósito: o audit log do GitHub registra que uma sessão de agente existiu e quem a iniciou, mas nunca o prompt local nem os argumentos. A tag vermelha é a frase para repetir em toda reunião de compliance.\n\n**[GANCHO PROVOCATIVO]**\nSe um auditor perguntar o que o agente rodou num laptop no mês passado, qual faixa responde?\n\n**[TRANSIÇÃO, para o próximo slide]**\nO diagrama do pipeline de evidência com onde cada artefato cai.\n\n**[TIMING]** ~1.5 min",
           'es': "**[APERTURA]**\nTres puertas hacia fuera del laptop. Dos las construyen ustedes; una la da la plataforma, y es la más angosta.\n\n**[NÚCLEO]**\nEl carril verde es el hook http: cada evento se vuelve un POST a su SIEM con el id de sesión, la decisión y un comando redactado. Los paquetes que ven moverse son esos eventos. El carril azul es OpenTelemetry: cada hook es un span en el trace de la sesión, y así prueban, meses después, que el guardrail corrió ese martes. El carril amarillo es punteado a propósito: el audit log de GitHub registra que una sesión de agente existió y quién la inició, pero nunca el prompt local ni los argumentos. La etiqueta roja es la frase para repetir en cada reunión de compliance.\n\n**[GANCHO PROVOCATIVO]**\nSi un auditor pregunta qué corrió el agente en un laptop el mes pasado, ¿qué carril responde?\n\n**[TRANSICIÓN, al siguiente slide]**\nEl diagrama del pipeline de evidencia con dónde cae cada artefacto.\n\n**[TIMING]** ~1.5 min"}),
 7: dict(fn=scene7, accent='yellow', eyebrow={'en': 'Scene · governance', 'pt-BR': 'Cena · governança', 'es': 'Escena · gobernanza'},
    title={'en': 'Three switches the developer can flip. One they cannot.', 'pt-BR': 'Três chaves que o desenvolvedor pode desligar. Uma que não pode.', 'es': 'Tres interruptores que el desarrollador puede apagar. Uno que no.'},
    keys={'who': {'en': 'delivered by MDM, re-fetched every hour', 'pt-BR': 'entregue pelo MDM, rebuscado a cada hora', 'es': 'entregado por MDM, recargado cada hora'}, 'how': {'en': 'most restrictive value wins across sources', 'pt-BR': 'o valor mais restritivo vence entre as fontes', 'es': 'el valor más restrictivo gana entre fuentes'}, 'note': {'en': 'a control the developer can edit is a convenience; a control only the admin can edit is governance', 'pt-BR': 'controle que o desenvolvedor edita é conveniência; controle que só o admin edita é governança', 'es': 'un control que el desarrollador edita es conveniencia; uno que solo edita el admin es gobernanza'}},
    caps=[('blue', {'en': ('disableAllHooks reaches three', 'User, repository and inline hooks can all be switched off from a file the developer owns. Useful for debugging, useless as a control.'), 'pt-BR': ('disableAllHooks alcança três', 'Hooks de usuário, de repositório e inline podem ser desligados num arquivo que o desenvolvedor controla. Útil para depurar, inútil como controle.'), 'es': ('disableAllHooks alcanza tres', 'Los hooks de usuario, de repositorio e inline pueden apagarse desde un archivo que el desarrollador controla. Útil para depurar, inútil como control.')}),
          ('red', {'en': ('Policy hooks stay locked', 'Root-owned files in policy.d or the registry load first, in every session, regardless of trust, and no flag turns them off.'), 'pt-BR': ('Policy hooks ficam trancados', 'Arquivos de dono root em policy.d ou no registro carregam primeiro, em toda sessão, independente de trust, e nenhuma flag os desliga.'), 'es': ('Los policy hooks quedan bloqueados', 'Archivos de root en policy.d o el registro cargan primero, en cada sesión, sin importar trust, y ninguna flag los apaga.')}),
          ('yellow', {'en': ('Managed settings close the gaps', 'allowManagedHooksOnly, deny rules and disableBypassPermissionsMode arrive through the MDM and beat every local value.'), 'pt-BR': ('Managed settings fecham as brechas', 'allowManagedHooksOnly, regras de deny e disableBypassPermissionsMode chegam pelo MDM e vencem qualquer valor local.'), 'es': ('Los managed settings cierran las brechas', 'allowManagedHooksOnly, reglas de deny y disableBypassPermissionsMode llegan por el MDM y ganan a cualquier valor local.')})],
    notes={'en': "**[OPENING]**\nWatch the switches. Three of them go off one by one. The fourth shakes and stays.\n\n**[CORE]**\nThe first three rows are the developer's world: user hooks, repository hooks, inline settings. Every one of them honors disableAllHooks, which is the right thing for debugging and the wrong thing to call a control. The fourth row is policy: root-owned, loaded first, immune to the flag, present even in an untrusted folder. Beside it, managed settings from the MDM do the same for permissions: allowManagedHooksOnly, deny rules, no bypass mode. When two sources disagree, the most restrictive value wins.\n\n**[PROVOCATIVE HOOK]**\nOpen your hooks folder. How many of those files could the developer delete before lunch?\n\n**[TRANSITION, to the next slide]**\nPolicy hooks in detail: where they live, what integrity they need, what they cannot do.\n\n**[TIMING]** ~1.5 min",
           'pt-BR': "**[ABERTURA]**\nOlha as chaves. Três apagam uma a uma. A quarta treme e fica.\n\n**[NÚCLEO]**\nAs três primeiras linhas são o mundo do desenvolvedor: hooks de usuário, de repositório, settings inline. Todas respeitam disableAllHooks, que é a coisa certa para depurar e a coisa errada para chamar de controle. A quarta linha é policy: dono root, carrega primeiro, imune à flag, presente até em pasta sem trust. Ao lado, os managed settings do MDM fazem o mesmo para permissões: allowManagedHooksOnly, regras de deny, sem modo bypass. Quando duas fontes discordam, o valor mais restritivo vence.\n\n**[GANCHO PROVOCATIVO]**\nAbra a sua pasta de hooks. Quantos daqueles arquivos o desenvolvedor conseguiria apagar antes do almoço?\n\n**[TRANSIÇÃO, para o próximo slide]**\nPolicy hooks em detalhe: onde vivem, que integridade precisam, o que não conseguem fazer.\n\n**[TIMING]** ~1.5 min",
           'es': "**[APERTURA]**\nMiren los interruptores. Tres se apagan uno a uno. El cuarto tiembla y se queda.\n\n**[NÚCLEO]**\nLas tres primeras filas son el mundo del desarrollador: hooks de usuario, de repositorio, settings inline. Todas respetan disableAllHooks, que es lo correcto para depurar y lo incorrecto para llamarlo control. La cuarta fila es policy: dueño root, carga primero, inmune a la flag, presente incluso en una carpeta sin trust. Al lado, los managed settings del MDM hacen lo mismo con los permisos: allowManagedHooksOnly, reglas de deny, sin modo bypass. Cuando dos fuentes discrepan, gana el valor más restrictivo.\n\n**[GANCHO PROVOCATIVO]**\nAbran su carpeta de hooks. ¿Cuántos de esos archivos podría borrar el desarrollador antes del almuerzo?\n\n**[TRANSICIÓN, al siguiente slide]**\nPolicy hooks en detalle: dónde viven, qué integridad necesitan, qué no pueden hacer.\n\n**[TIMING]** ~1.5 min"}),
 8: dict(fn=scene8, accent='blue', eyebrow={'en': 'Scene · the climb', 'pt-BR': 'Cena · a subida', 'es': 'Escena · la subida'},
    title={'en': 'Four steps, ninety days, from a session banner to a policy nobody turns off.', 'pt-BR': 'Quatro degraus, noventa dias, de um banner de sessão a uma política que ninguém desliga.', 'es': 'Cuatro escalones, noventa días, de un banner de sesión a una política que nadie apaga.'},
    keys={'s1': {'en': 'Observe', 'pt-BR': 'Observar', 'es': 'Observar'}, 's2': {'en': 'Protect', 'pt-BR': 'Proteger', 'es': 'Proteger'}, 's3': {'en': 'Automate', 'pt-BR': 'Automatizar', 'es': 'Automatizar'}, 's4': {'en': 'Govern', 'pt-BR': 'Governar', 'es': 'Gobernar'},
          'w1': {'en': 'week 1 · banner, log', 'pt-BR': 'semana 1 · banner, log', 'es': 'semana 1 · banner, log'}, 'w2': {'en': 'weeks 2 to 4 · deny', 'pt-BR': 'semanas 2 a 4 · deny', 'es': 'semanas 2 a 4 · deny'}, 'w3': {'en': 'month 2 · tests, SIEM', 'pt-BR': 'mês 2 · testes, SIEM', 'es': 'mes 2 · tests, SIEM'}, 'w4': {'en': 'month 3 · policy, plugin', 'pt-BR': 'mês 3 · policy, plugin', 'es': 'mes 3 · policy, plugin'},
          'goal': {'en': 'controls the developer cannot change', 'pt-BR': 'controles que o desenvolvedor não muda', 'es': 'controles que el desarrollador no cambia'}},
    caps=[('blue', {'en': ('Start by watching', 'A banner and a JSONL log cost an afternoon and teach the payload. Nobody argues with a hook that only observes.'), 'pt-BR': ('Comece observando', 'Um banner e um log JSONL custam uma tarde e ensinam o payload. Ninguém discute com um hook que só observa.'), 'es': ('Empiecen observando', 'Un banner y un log JSONL cuestan una tarde y enseñan el payload. Nadie discute con un hook que solo observa.')}),
          ('green', {'en': ('Then protect and automate', 'Deny the five destructive patterns with reasons, gate the stop on tests, format after edits, ship events to the SIEM. Measure false denies per week.'), 'pt-BR': ('Depois proteja e automatize', 'Negue os cinco padrões destrutivos com motivos, condicione o stop aos testes, formate depois das edições, envie eventos ao SIEM. Meça falsos denies por semana.'), 'es': ('Luego protejan y automaticen', 'Nieguen los cinco patrones destructivos con motivos, condicionen el stop a los tests, formateen tras las ediciones, envíen eventos al SIEM. Midan falsos denies por semana.')}),
          ('red', {'en': ('Govern last, on purpose', 'Policy hooks, managed settings and a platform plugin come after trust exists. A program that starts here is disabled by lunchtime.'), 'pt-BR': ('Governe por último, de propósito', 'Policy hooks, managed settings e um plugin de plataforma vêm depois de existir confiança. Um programa que começa aqui é desligado antes do almoço.'), 'es': ('Gobiernen al final, a propósito', 'Policy hooks, managed settings y un plugin de plataforma llegan después de que existe confianza. Un programa que empieza aquí se apaga antes del almuerzo.')})],
    notes={'en': "**[OPENING]**\nThe dot climbs. Four steps, each one taller than the last, and the order is not negotiable.\n\n**[CORE]**\nStep one is observation: a session banner and a tool log. It costs an afternoon and it earns the right to do step two, because now the team has seen the payload and trusts the mechanism. Step two is protection: the five destructive patterns denied with reasons, the demo marker, the metric of false denies per week. Step three is automation, which is where developers start to like hooks: tests before stop, format after edit, the SIEM door. Step four is governance: policy hooks, managed settings, a plugin. Teams that start at step four get disabled by lunchtime; teams that climb get there in ninety days with a program people already trust.\n\n**[PROVOCATIVE HOOK]**\nWhich step is your organization on today, and which one does your security team think you are on?\n\n**[TRANSITION, to the next slide]**\nThe maturity ladder with the concrete checklist per step.\n\n**[TIMING]** ~2 min",
           'pt-BR': "**[ABERTURA]**\nO ponto sobe. Quatro degraus, cada um mais alto que o anterior, e a ordem não é negociável.\n\n**[NÚCLEO]**\nO degrau um é observação: um banner de sessão e um log de tools. Custa uma tarde e compra o direito ao degrau dois, porque agora o time viu o payload e confia no mecanismo. O degrau dois é proteção: os cinco padrões destrutivos negados com motivos, o marcador de demo, a métrica de falsos denies por semana. O degrau três é automação, onde os desenvolvedores começam a gostar de hooks: testes antes do stop, formato depois da edição, a porta do SIEM. O degrau quatro é governança: policy hooks, managed settings, um plugin. Times que começam no degrau quatro são desligados antes do almoço; times que sobem chegam lá em noventa dias com um programa em que as pessoas já confiam.\n\n**[GANCHO PROVOCATIVO]**\nEm que degrau a sua organização está hoje, e em qual o seu time de segurança acha que está?\n\n**[TRANSIÇÃO, para o próximo slide]**\nA escada de maturidade com o checklist concreto por degrau.\n\n**[TIMING]** ~2 min",
           'es': "**[APERTURA]**\nEl punto sube. Cuatro escalones, cada uno más alto que el anterior, y el orden no es negociable.\n\n**[NÚCLEO]**\nEl escalón uno es observación: un banner de sesión y un log de tools. Cuesta una tarde y compra el derecho al escalón dos, porque ahora el equipo vio el payload y confía en el mecanismo. El escalón dos es protección: los cinco patrones destructivos negados con motivos, el marcador de demo, la métrica de falsos denies por semana. El escalón tres es automatización, donde los desarrolladores empiezan a querer a los hooks: tests antes del stop, formato tras la edición, la puerta del SIEM. El escalón cuatro es gobernanza: policy hooks, managed settings, un plugin. Los equipos que empiezan en el cuatro quedan apagados antes del almuerzo; los que suben llegan en noventa días con un programa en el que la gente ya confía.\n\n**[GANCHO PROVOCATIVO]**\n¿En qué escalón está su organización hoy, y en cuál cree su equipo de seguridad que está?\n\n**[TRANSICIÓN, al siguiente slide]**\nLa escalera de madurez con el checklist concreto por escalón.\n\n**[TIMING]** ~2 min"}),
}


SCENE_KINDS = {
    1: 'lifecycle',
    2: 'input-output',
    3: 'convergence',
    4: 'gate',
    5: 'loop',
    6: 'lanes',
    7: 'flip-lock',
    8: 'maturity',
}


def scene_svg(n):
    kind = SCENE_KINDS[n]
    return f'<svg class="scn" data-scene-kind="{kind}" viewBox="0 0 1120 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="{kind.replace("-", " ")} animated scene">{MARKER}{SCENES[n]["fn"]()}</svg>'

def scene_caps(n, key, reg):
    """reg(key, en, pt, es) registers an i18n string and returns the data-i18n attribute."""
    sc = SCENES[n]; out = []
    for i, (col, caps) in enumerate(sc['caps'], 1):
        out.append(f'<div class="cap" style="--c:var(--ps-color-ms-{col}-500);--i:{i-1}"><b {reg(f"{key}.c{i}t", caps["en"][0], caps["pt-BR"][0], caps["es"][0])}>{caps["en"][0]}</b><span {reg(f"{key}.c{i}d", caps["en"][1], caps["pt-BR"][1], caps["es"][1])}>{caps["en"][1]}</span></div>')
    return '<div class="scene__caps">' + ''.join(out) + '</div>'
