name: External links

on:
  pull_request:
  schedule:
    - cron: "17 8 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: lycheeverse/lychee-action@v2.9.0
        with:
          args: >-
            --no-progress
            --exclude-path legacy
            --accept 200,204,206,429
            './**/*.md'
          fail: true
